# Generated by Django 3.2.7 on 2021-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='avalicoes',
            field=models.ManyToManyField(to='avaliacoes.Avalicao'),
        ),
    ]
