# Generated by Django 3.2.7 on 2021-10-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pontoturistico_enderecos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='avalicoes',
            new_name='avaliacoes',
        ),
    ]
