# Generated by Django 3.2.7 on 2021-11-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_rename_avalicao_avaliacao'),
        ('comentarios', '0001_initial'),
        ('core', '0009_pontoturistico_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, null=True, to='avaliacoes.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(blank=True, null=True, to='comentarios.Comentario'),
        ),
    ]
