# Generated by Django 3.2.7 on 2021-11-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_atracao_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
